In [1]:
import numpy as np

In [2]:
def calculate(list):
# Mensagem de erro caso a lista não contenha 9 dígitos
  if len(list) != 9:
    raise ValueError('List must contain nine numbers.')

# Rearranjando a lista em uma array 3x3 do NumPy
  list = np.array(list).reshape(3, 3)

# Mean
  mean = [list.mean(axis=0).tolist(), list.mean(axis=1).tolist(), np.mean(list).tolist()]

# Variance
  variance = [list.var(axis=0).tolist(), list.var(axis=1).tolist(), np.var(list).tolist()]
  
# Standard Deviation
  std_dev = [list.std(axis=0).tolist(), list.std(axis=1).tolist(), np.std(list).tolist()]
  
# Max
  max = [list.max(axis=0).tolist(), list.max(axis=1).tolist(), np.max(list).tolist()]
  
# Min
  min = [list.min(axis=0).tolist(), list.min(axis=1).tolist(), np.min(list).tolist()]
  
# Sum
  sum = [list.sum(axis=0).tolist(), list.sum(axis=1).tolist(), np.sum(list).tolist()]

  return {
      'mean': mean,
      'variance': variance,
      'standard deviation': std_dev,
      'max': max,
      'min': min,
      'sum': sum
  }

In [4]:
calculate([1, 2, 3, 4, 5, 6, 7, 8, 9])

{'mean': [[4.0, 5.0, 6.0], [2.0, 5.0, 8.0], 5.0],
 'variance': [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666667],
 'standard deviation': [[2.449489742783178,
   2.449489742783178,
   2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 'max': [[7, 8, 9], [3, 6, 9], 9],
 'min': [[1, 2, 3], [1, 4, 7], 1],
 'sum': [[12, 15, 18], [6, 15, 24], 45]}

In [17]:
# Passo a passo

list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Convertendo a lista (Python) em Series (Panda), e rearranjando sua estrutura para 3x3
matriz = np.array(list).reshape(3, 3)
print(matriz, '\n')

# Cálculo com linhas e colunas (média)

  # Média das colunas da matriz 3x3
mean1 = matriz.mean(axis = 0).tolist()
print(mean1, '\n')

  # Média das linhas da matriz 3x3
mean2 = matriz.mean(axis = 1).tolist()
print(mean2, '\n')

  # Média da matriz
mean3 = np.mean(matriz).tolist()
print(mean3)

# Essa metodologia se repete para os outros cálculos, no fim, passamos todos os itens para uma lista com o comando 'tolist()' e printamos os resultados

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[4.0, 5.0, 6.0] 

[2.0, 5.0, 8.0] 

5.0
